/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tsyc.ui;

import com.tsyc.operations.BasicOperations;
import com.tysc.utils.AudioManager;
import com.tysc.utils.Plotter;
import com.tysc.utils.AudioRecorder;
import javax.swing.JOptionPane;

/**
 *
 * @author Yahir
 */
public class Recorder extends javax.swing.JFrame {

    Thread recorder;
    public Recorder() {
        initComponents();
        btnPlayInput.setEnabled(false);
        btnPlayOutput.setEnabled(false);
        btnStop.setEnabled(false);
        btnPlotInput.setEnabled(false);
        btnPlotOutput.setEnabled(false);
        btnAmp.setEnabled(false);
        btnAtenuacion.setEnabled(false);
        btnDesplazamiento.setEnabled(false);
        btnReflejo.setEnabled(false);
        btnIntCero.setEnabled(false);
        btnIntEscalon.setEnabled(false);
        btnIntLineal.setEnabled(false);
        btnDiezmación.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnPlotInput = new javax.swing.JButton();
        btnPlayInput = new javax.swing.JButton();
        btnPlotOutput = new javax.swing.JButton();
        btnPlayOutput = new javax.swing.JButton();
        btnAmp = new javax.swing.JButton();
        btnAtenuacion = new javax.swing.JButton();
        btnDesplazamiento = new javax.swing.JButton();
        btnReflejo = new javax.swing.JButton();
        btnIntCero = new javax.swing.JButton();
        btnIntEscalon = new javax.swing.JButton();
        btnIntLineal = new javax.swing.JButton();
        btnDiezmación = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Grabar");
        btnStart.setActionCommand("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Detener");
        btnStop.setActionCommand("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnPlotInput.setText("Graficar entrada");
        btnPlotInput.setActionCommand("PlotInput");
        btnPlotInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlotInputActionPerformed(evt);
            }
        });

        btnPlayInput.setActionCommand("PlayInput");
        btnPlayInput.setLabel("Reproducir entrada");
        btnPlayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayInputActionPerformed(evt);
            }
        });

        btnPlotOutput.setText("Graficar salida");
        btnPlotOutput.setActionCommand("PlotOutput");
        btnPlotOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlotOutputActionPerformed(evt);
            }
        });

        btnPlayOutput.setText("Reproducir salida");
        btnPlayOutput.setActionCommand("PlayOutput");
        btnPlayOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayOutputActionPerformed(evt);
            }
        });

        btnAmp.setText("Amplificación");
        btnAmp.setActionCommand("btnAmp");
        btnAmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmpActionPerformed(evt);
            }
        });

        btnAtenuacion.setText("Atenuación");
        btnAtenuacion.setActionCommand("Atenuacion");
        btnAtenuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenuacionActionPerformed(evt);
            }
        });

        btnDesplazamiento.setText("Desplazamiento");
        btnDesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesplazamientoActionPerformed(evt);
            }
        });

        btnReflejo.setText("Reflejo");
        btnReflejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflejoActionPerformed(evt);
            }
        });

        btnIntCero.setText("Interpolación Cero");
        btnIntCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntCeroActionPerformed(evt);
            }
        });

        btnIntEscalon.setText("Interpolación Escalón");
        btnIntEscalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntEscalonActionPerformed(evt);
            }
        });

        btnIntLineal.setText("Interpolación lineal");
        btnIntLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntLinealActionPerformed(evt);
            }
        });

        btnDiezmación.setText("Diezmación");
        btnDiezmación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiezmaciónActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPlotOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlotInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlayInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlayOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAmp)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtenuacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesplazamiento)
                        .addGap(18, 18, 18)
                        .addComponent(btnReflejo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIntCero)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntEscalon)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntLineal))
                    .addComponent(btnDiezmación))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlotInput)
                    .addComponent(btnPlayInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlotOutput)
                    .addComponent(btnPlayOutput))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAmp)
                    .addComponent(btnAtenuacion)
                    .addComponent(btnDesplazamiento)
                    .addComponent(btnReflejo))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntCero)
                    .addComponent(btnIntEscalon)
                    .addComponent(btnIntLineal))
                .addGap(18, 18, 18)
                .addComponent(btnDiezmación)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        btnPlotInput.getAccessibleContext().setAccessibleName("PlotInput");
        btnPlayInput.getAccessibleContext().setAccessibleName("PlayInput");
        btnPlotOutput.getAccessibleContext().setAccessibleName("btnPlotOutput");
        btnPlayOutput.getAccessibleContext().setAccessibleName("btnPlayOutput");
        btnAmp.getAccessibleContext().setAccessibleName("Amp");
        btnAtenuacion.getAccessibleContext().setAccessibleName("Atenuacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        recorder = new Thread(new AudioRecorder());
        recorder.start();
        btnStart.setEnabled(false);
        btnPlayInput.setEnabled(false);
        btnPlotInput.setEnabled(false);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        recorder.stop();
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
        btnPlotInput.setEnabled(true);
        btnPlayInput.setEnabled(true);
        btnAmp.setEnabled(true);
        btnAtenuacion.setEnabled(true);
        btnDesplazamiento.setEnabled(true);
        btnReflejo.setEnabled(true);
        btnIntCero.setEnabled(true);
        btnIntEscalon.setEnabled(true);
        btnIntLineal.setEnabled(true);
        btnDiezmación.setEnabled(true);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnPlotInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlotInputActionPerformed
        double[] data = AudioManager.read("Grabacion.wav");
        
        Plotter plotter = new Plotter(data);
        plotter.plotAudio("input");
        PlotDisplay p = new PlotDisplay("input");
    }//GEN-LAST:event_btnPlotInputActionPerformed

    private void btnPlayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayInputActionPerformed
        btnPlayInput.setEnabled(false);
        AudioManager.play("Grabacion.wav");
        btnPlayInput.setEnabled(true);
    }//GEN-LAST:event_btnPlayInputActionPerformed

    private void btnPlotOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlotOutputActionPerformed
        double[] data = AudioManager.read("NuevaGrabacion.wav");
        
        Plotter plotter = new Plotter(data);
        plotter.plotAudio("output");
        PlotDisplay p = new PlotDisplay("output");
    }//GEN-LAST:event_btnPlotOutputActionPerformed

    private void btnPlayOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayOutputActionPerformed
        btnPlayOutput.setEnabled(false);
        AudioManager.play("NuevaGrabacion.wav");
        btnPlayOutput.setEnabled(true);
    }//GEN-LAST:event_btnPlayOutputActionPerformed

    private void btnAmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmpActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa la constante de amplificación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.amplificacion(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnAmpActionPerformed

    private void btnAtenuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenuacionActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa la constante de atenuación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.atenuacion(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnAtenuacionActionPerformed

    private void btnDesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesplazamientoActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa los segundos a desplazar", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.desplazamiento(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnDesplazamientoActionPerformed

    private void btnReflejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflejoActionPerformed
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.reflejo(data);
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnReflejoActionPerformed

    private void btnIntCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntCeroActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa el factor de interpolación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.interpolacionCero(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnIntCeroActionPerformed

    private void btnIntEscalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntEscalonActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa el factor de interpolación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.interpolacionEscalon(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnIntEscalonActionPerformed

    private void btnIntLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntLinealActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa el factor de interpolación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.interpolacionLineal(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnIntLinealActionPerformed

    private void btnDiezmaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiezmaciónActionPerformed
        String k = JOptionPane.showInputDialog(this, "Ingresa el factor de diezmación", null);
        double[] data = AudioManager.read("Grabacion.wav");
        
        BasicOperations.diezmacion(data, Integer.parseInt(k));
        btnPlayOutput.setEnabled(true);
        btnPlotOutput.setEnabled(true);
    }//GEN-LAST:event_btnDiezmaciónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Recorder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmp;
    private javax.swing.JButton btnAtenuacion;
    private javax.swing.JButton btnDesplazamiento;
    private javax.swing.JButton btnDiezmación;
    private javax.swing.JButton btnIntCero;
    private javax.swing.JButton btnIntEscalon;
    private javax.swing.JButton btnIntLineal;
    private javax.swing.JButton btnPlayInput;
    private javax.swing.JButton btnPlayOutput;
    private javax.swing.JButton btnPlotInput;
    private javax.swing.JButton btnPlotOutput;
    private javax.swing.JButton btnReflejo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables
}
